# signup-bot-frontend/.streamlit/secrets.toml

# Replace with the ACTUAL public static URL from ngrok
# This MUST point to where signup_bot_api_runner.py is listening (port 5001)
SIGNUP_API_URL = "https://yearly-profound-crayfish.ngrok-free.app"  

# This MUST match the SIGNUP_API_KEY from your signupbot/.env file
SIGNUP_API_KEY = "another_secure_random_key_789_xyz"